#########################################################
#Copyright (C): Henri Payno, Axel Delsol, 				#
#Laboratoire de Physique de Clermont UMR 6533 CNRS-UCA	#
#														#
#This software is distributed under the terms			#
#of the GNU Lesser General  Public Licence (LGPL)		#
#See LICENSE.md for further details						#
#########################################################
########################################################################
# Define detector parameter
# In this example, you only need to set the size of the box

/detector/size 800 um

########################################################################
# Seed parameter

/random/setSeeds 123456 1

########################################################################
# Define the physics process you want to simulate
/run/particle/verbose 0
/run/verbose 0
# set the maximum step allowed
/cpop/physics/stepMax 0.0001 mm

# set the physics list you want to use.
# candidates : emstandard emstandard_opt1 emstandard_opt2 emstandard_opt3 emstandard_opt4 emlivermore empenelope emDNAphysics emDNAphysics_opt2
/cpop/physics/physicsList emstandard_opt4

# Those commands are defined in G4EmParametersMessenger.cc
#/process/eLoss/minKinEnergy 100 eV
#/process/eLoss/maxKinEnergy 1 GeV
#/process/em/auger true

# Those commands are defined in G4ProductionCutsTableMessenger.cc
#/cuts/setLowEdge 0.0001 mm


########################################################################
# Define CPOP parameters

# allow cpop to print cpop parameters at the beginning of the simulation
/cpop/population/verbose 1

# set the population file (relative path from the current directory)
#/cpop/population/input data/geometries/Radius95um_25CP.cfg.xml
/cpop/population/input data/geometries/Radius95um_50CP.cfg.xml
#/cpop/population/input data/geometries/Radius95um_75CP.cfg.xml

# set representation parameters
/cpop/population/numberFacet 80
/cpop/population/deltaRef !

# define necrosis, intermediary and external regions
# Necrosis region     : from 0                                to internalRatio*spheroidRadius
# Intermediary region : from internalRatio*spheroidRadius     to intermediaryRatio*spheroidRadius
# External region     : from intermediaryRatio*spheroidRadius to spheroidRadius
/cpop/population/internalRatio 0.01
/cpop/population/intermediaryRatio 0.52

# set sampling cell ie number of cell per region to observe
/cpop/population/sampling !

# Get info at the stepping level
/cpop/population/stepInfo 0
# Get info at the event level
/cpop/population/eventInfo 1

#Write positions, directions and energies of primary particles in a .txt
#/cpop/population/writeInfoPrimariesTxt yes infoPrimaries0.txt

# Initialize cpop
/cpop/population/init


########################################################################
# Initialiaze and geant4
/run/initialize

########################################################################
# Define sources

# add a particle source
/cpop/source/addDistribution radionuclide

# set the primary particles to send from a source
#/cpop/source/radionuclide/particle alpha
/cpop/source/radionuclide/ion 3 7

/cpop/source/radionuclide/spectrum data/spectra/At211.txt

# set the number of sources in the spheroid
/cpop/source/radionuclide/totalSource 200

# set the number of particles emitted from one source
/cpop/source/radionuclide/particlesPerSource 1

# set to 1 to have all sources in a cell located in the same place
# set to 0 for a random distribution of sources in a cell
/cpop/source/radionuclide/only_one_position_for_all_particles_on_a_cell 0

# set the source distribution in each region
# requirement : the sum of your value must be equal to totalSource
# region order : necrosis intermediary external
/cpop/source/radionuclide/distributionInRegion  0 0 200

# set the sources distribution in a cell containing a source
# organelle order : CellMembrane Nucleus NucleusMembrane Cytoplasm
# Put a float proportion between 0 and 1 
/cpop/source/radionuclide/distributionInCell 0 1 0 0

# Activate diffusion of radionuclide's daughter (for At-211 only)
#/cpop/source/daughterDiffusion yes 0.5

#Choose a txt file with positions and directions and choose a method to use them on
#the primaries  of your simulation
#methods: SamePositions_SameDirections, SamePositions_OppositeDirections 
#/cpop/source/usePositionsDirectionsTxt infoPrimaries2.txt SamePositions_OppositeDirections


# set the maximum number of sources per cell, in each region.
# region order : necrosis intermediary external
/cpop/source/radionuclide/maxSourcesPerCell 0 10000 10000

# set the percentage of labeled cells in each region
# region order : necrosis intermediary external
/cpop/source/radionuclide/cellLabelingPercentagePerRegion 100 100 100

# initialize the sources
/cpop/source/init

########################################################################
# Set the output file

# defined in G4FileMessenger.cc
/analysis/setFileName output/output.root


########################################################################
# Start the simulation

# defined in G4RunMessenger.cc
/run/printProgress 1000

# requirement : the value should be equal to 
# totalSource * particlesPerSource
/run/beamOn 200
