#include "CellFactory.hh"
#include "File_CPOP_Data.hh"
#include "File_Utils_TXT.hh"
#include "InformationSystemManager.hh"

#include "SimpleDiscoidalCell.hh"
#include "SimpleSpheroidalCell.hh"
#include "SpheresSDelimitation.hh"

#include <QDomElement>
#include <QFile>

using namespace Settings::nCell;

namespace IO::CPOP
{

/// \param writable The entity to save
/// \param path The output file path
void save(Writable* writable, QString path) {
	assert(writable);
	QFile xmlFile(path);
	if(!xmlFile.open(QIODevice::WriteOnly)) {
		std::string mess = "Error - can't save - cannot open the requested " + path.toStdString();
		InformationSystemManager::getInstance()->Message(InformationSystemManager::CANT_PROCESS_MES, mess, "FILE::XML::getAgents");
		return;
	}

	QXmlStreamWriter writer(&xmlFile);
	writer.setAutoFormatting(true);
	writer.writeStartDocument("1.0");
	writer.writeComment("XML defining a cell porpulation, generated by CPOP");

	{
		writer.writeStartElement(save_flag);
		writable->write(writer);
		writer.writeEndElement(); // save_flag
	}

	writer.writeEndDocument();
}

}
