/cpop/population/verbose 1
/cpop/population/input population.xml
/cpop/population/numberFacet 100
/cpop/population/deltaRef !
/cpop/population/internalRatio 0.25
/cpop/population/intermediaryRatio 0.75
/cpop/population/sampling 12
/cpop/population/init

# Add a electron source
/cpop/source/addHomogeneous electron
/cpop/source/electron/particle e-
/cpop/source/electron/spectrum eSpectrum_550um.spec
/cpop/source/electron/totalParticle 1000

# Add a gadolinium source
/cpop/source/addDistributed gadolinium
/cpop/source/gadolinium/particle e-
/cpop/source/gadolinium/spectrum eSpectrum_550um.spec
/cpop/source/gadolinium/totalNanoparticle 6
/cpop/source/gadolinium/particlePerNano 100
# necrosis intermediary external
/cpop/source/gadolinium/distributionInRegion  1 2 3
# CellMembrane Nucleoplasm NucleusMembrane Cytoplasm
/cpop/source/gadolinium/distributionInCell 1 0 0 0

/cpop/source/init
