/cpop/population/verbose 1
/cpop/population/input population.xml
/cpop/population/numberFacet 100
/cpop/population/deltaRef !
/cpop/population/internalRatio 0.25
/cpop/population/intermediaryRatio 0.75
/cpop/population/sampling 12
/cpop/population/init


# Add a electron source
/cpop/source/addUniform electron
/cpop/source/electron/particle e-
/cpop/source/electron/spectrum eSpectrum_550um.spec
/cpop/source/electron/totalParticle 1000
