#########################################################
#Copyright (C): Henri Payno, Axel Delsol, 				#
#Laboratoire de Physique de Clermont UMR 6533 CNRS-UCA	#
#														#
#This software is distributed under the terms			#
#of the GNU Lesser General  Public Licence (LGPL)		#
#See LICENSE.md for further details						#
#########################################################
########################################################################
# Define detector parameter
# In this example, you only need to set the size of the box

/detector/size 800 um

########################################################################
# Seed parameter

/random/setSeeds 123456 3

########################################################################
# Define the physics process you want to simulate
/run/particle/verbose 0
/run/verbose 0
# set the maximum step allowed
/cpop/physics/stepMax 0.0001 mm

# set the physics list you want to use.
# candidates : emstandard emstandard_opt1 emstandard_opt2 emstandard_opt3 emstandard_opt4 emlivermore empenelope emDNAphysics emDNAphysics_opt2
/cpop/physics/physicsList emstandard_opt4
#/cpop/physics/physicsList emDNAphysics_opt2


# Those commands are defined in G4EmParametersMessenger.cc
#/process/eLoss/minKinEnergy 100 eV
#/process/eLoss/maxKinEnergy 1 GeV
#/process/em/auger true

# Those commands are defined in G4ProductionCutsTableMessenger.cc
#/cuts/setLowEdge 0.0001 mm


########################################################################
# Define CPOP parameters

# allow cpop to print cpop parameters at the beginning of the simulation
/cpop/population/verbose 1

# set the population file (relative path from the current directory)
#/cpop/population/input data/Radius95um_25CP.cfg.xml
#/cpop/population/input data/Radius95um_50CP.cfg.xml
/cpop/population/input data/Radius100um_40CP.cfg.xml

# set representation parameters
/cpop/population/numberFacet 80
/cpop/population/deltaRef !

# define necrosis, intermediary and external regions
# Necrosis region     : from 0                   to 0.01*spheroidRadius
# Intermediary region : from 0.01*spheroidRadius to 0.52*spheroidRadius
# External region     : from 0.52*spheroidRadius to spheroidRadius
/cpop/population/internalRatio 0.01
/cpop/population/intermediaryRatio 0.52

# set sampling cell ie number of cell per region to observe
/cpop/population/sampling !

# Get info at the stepping level
/cpop/population/stepInfo 0
# Get info at the event level
/cpop/population/eventInfo 1
##### For now, only one option can be chosen ####

# Initialize cpop
/cpop/population/init


########################################################################
# Initialiaze and geant4
/run/initialize

########################################################################
# Define sources

# add a particle source
/cpop/source/addNanoparticle gadolinium

# set the secondaries particle to generate from a particle
/cpop/source/gadolinium/particle alpha

/cpop/source/gadolinium/spectrum data/At211.spec
#/cpop/source/gadolinium/spectrum data/Bi213.spec
#/cpop/source/gadolinium/spectrum data/Po210.spec

# set the number of nanoparticle in the spheroid

/cpop/source/gadolinium/totalNanoparticle 7916

# set the number of secondaries for one nanoparticle
/cpop/source/gadolinium/particlePerNano 1

# Allow only one position for all particles generated on the same cell
/cpop/source/gadolinium/only_one_position_for_all_particles_on_a_cell 0

# set the nanoparticle distribution in each region
# requirement : the sum of your value must be equal to totalNanoparticle
# region order : necrosis intermediary external
#/cpop/source/gadolinium/distributionInRegion  0 127 714
/cpop/source/gadolinium/distributionInRegion  0 1068 6848

# set the secondaries distribution  in a cell contaning a nanoparticle
# organelle order : CellMembrane Nucleoplasm NucleusMembrane Cytoplasm
# Nucleoplasm=Nucleus, for Homogeneous : put 0.5 for Nucleoplasm and Cytoplasm
/cpop/source/gadolinium/distributionInCell 1 0 0 0

# Activate diffusion of radionuclide's daughter
/cpop/source/daughterDiffusion no


# set the maximum number of nanoparticle per cell, in each region. If total number of nanoparticle = number of cells * maximum number of nanoparticles per cell, all cells will have the maximum amount of nanoparticles
# region order : necrosis intermediary external
/cpop/source/gadolinium/maxNanoparticlePerCell 0 4 4

# set the percentage of labeled cells in each region
# region order : necrosis intermediary external
/cpop/source/gadolinium/cellLabelingPercentagePerRegion 100 100 100

# initialize the sources
/cpop/source/init

########################################################################
# Set the output file

# defined in G4FileMessenger.cc
/analysis/setFileName output/outputMembrane/output_3.root


########################################################################
# Start the simulation

# defined in G4RunMessenger.cc
/run/printProgress 1000

# requirement : the value should be equal to 
# totalParticle + totalNanoparticle * particlePerNano
/run/beamOn 7916
